name: run-test
on: 
  workflow_dispatch:
    inputs:
      caption:
        description: "Workflow caption:"
        required: false
        default: "HELLO WORLD!"
# jobs:
#   my-job:
#   caption: ${{ github.event.inputs.caption }}


# name: manual workflow

# on:
#   workflow_dispatch:

jobs:
  job1:
  caption: ${{ github.event.inputs.caption }}
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.sha }}

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Hello world
        run: echo "execitededdeded"
