# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ github-action-for-docker-and-schedule-event ]
  pull_request:
    branches: [ github-action-for-docker-and-schedule-event ]
  schedule:
    - cron: '0 12 * * *'
  repository_dispatch:

jobs:
  job1:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: print env
        run: env

      - name: Validate code
        run: mvn validate

      - name: Compile
        run: mvn clean compile

      - name: Testing
        run: mvn test

      - name: Create artifact
        run: mvn -B package --file pom.xml

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: sakshigawande12/maven-app:0.1

      - name: Run Snyk to check Docker image for vulnerabilities
          # Snyk can be used to break the build when it detects vulnerabilities.
          # In this case we want to upload the issues to GitHub Code Scanning
        continue-on-error: true
        uses: snyk/actions/docker@master
        env:
            # In order to use the Snyk Action you will need to have a Snyk API token.
            # More details in https://github.com/snyk/actions#getting-your-snyk-token
            # or you can signup for free at https://snyk.co/SignUpGH
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: sakshigawande12/maven-app:0.1
          args: --file=Dockerfile
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v1
        with:
        sarif_file: snyk.sarif
